# Generated by Django 2.2.24 on 2021-12-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_claim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='user',
            new_name='name',
        ),
    ]
