# Generated by Django 2.2.24 on 2021-12-19 09:37
import phonenumbers
from django.db import migrations


def normalize_phone_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.all():
        phone = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(phone):
            pure_phone = phonenumbers.format_number(
                phone,
                phonenumbers.PhoneNumberFormat.E164
            )
            flat.owner_pure_phone = pure_phone
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20211219_1236'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_number)
    ]
