# Generated by Django 2.2.24 on 2021-12-19 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20211219_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='name',
            new_name='owner',
        ),
    ]
