# Generated by Django 2.2.24 on 2021-12-30 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_auto_20211219_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='name',
            new_name='owner',
        ),
    ]
